version: '3.8'

services:
  odoo:
    build: .
    ports:
      - "10000:10000"
    environment:
      - DB_HOST=dpg-d17blgh5pdvs7386ecn0-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_USER=odoo_db_hu7t_user
      - DB_PASSWORD=5ji4IDqrKXRsVaWL4OYf121C3NCjBpWd
      - DB_NAME=odoo_db_hu7t
      - PORT=10000
    volumes:
      - ./odoo_oncef:/mnt/extra-addons
    depends_on:
      - db
    restart: unless-stopped

  # Optional: Local PostgreSQL for development
  # Comment out if using Render database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo_local
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: