  services:
    odoo:
      image: odoo:18
      container_name: odoo18
      depends_on:
        - postgres
      ports:
        - "8080:8069"
      environment:
        HOST: postgres
        USER: odoo
        PASSWORD: odoo
      volumes:
        - odoo-data:/var/lib/odoo
        - ./odoo_oncef:/mnt/extra-addons
      restart: unless-stopped

    postgres:
      image: postgres:15
      container_name: postgres_odoo
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: odoo
        POSTGRES_PASSWORD: odoo 
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - postgres-data:/var/lib/postgresql/data/pgdata
      restart: unless-stopped

  volumes:
    odoo-data:
    postgres-data: