services:
  - type: web
    name: odoo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000

databases:
  - name: odoo-db
    databaseName: odoo_db_hu7t
    plan: free