services:
  - type: web    name: odoo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    port: 8069
    envVars:      - key: DB_HOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: odoo-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: odoo-db
          property: database
      - key: PORT
        value: 8069
      - key: HOST
        fromDatabase:
          name: odoo-db
          property: host

databases:
  - name: odoo-db
    databaseName: postgres
    plan: free