services:
  - type: web
    name: odoo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    port: 8069
    envVars:
      - key: PORT
        value: 8069
      - key: DB_HOST
        fromDatabase:
          name: odoo-db
          property: host      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: DB_NAME
        value: odoo_db_hu7t
      - key: INIT_DB
        value: "true"

databases:
  - name: odoo-db
    databaseName: odoo_db_hu7t
    plan: free