services:
  - type: web
    name: odoo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    ports:
      - port: 8069
    envVars:
      - key: PORT
        value: 8069
      - key: HOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: POSTGRES_DB
        value: postgres
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DB_FILTER
        value: ".*"

databases:
  - name: odoo-db
    databaseName: postgres
    user: postgres
    plan: free
