services:
  - type: web
    name: odoo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    # Explicitly remove any database environment variables that might conflict
    envVars:
      - key: DATABASE_URL
        value: ""