services:
  - type: web
    name: odoo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: HOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: PORT
        value: 10000
      - key: PGHOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: PGUSER
        fromDatabase:
          name: odoo-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: PGPORT
        value: 5432

databases:
  - name: odoo-db
    databaseName: postgres
    plan: free