services:
  - type: web
    name: odoo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    ports:
      - port: 8069
    envVars:
      - key: PORT
        value: 8069
      - key: HOST
        value: dpg-d17blgh5pdvs7386ecn0-a
      - key: DB_PORT
        value: 5432
      - key: POSTGRES_USER
        value: odoo_db_hu7t_user
      - key: POSTGRES_PASSWORD
        value: 5ji4IDqrKXRsVaWL4OYf121C3NCjBpWd
      - key: POSTGRES_DB
        value: odoo_db_hu7t
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: DB_FILTER
        value: ".*"
      - key: HTTP_PORT
        value: 8069
      - key: LONGPOLLING_PORT
        value: 8072

databases:
  - name: odoo-db
    databaseName: odoo_db_hu7t
    user: odoo_db_hu7t_user
    plan: free
